package main

import "testing"

func TestLev(t *testing.T) {
	type Lev struct {
		word   string
		result int
	}
	lev_tests := map[string]Lev{
		"band":      {word: "band", result: 0},
		"bare":      {word: "bear", result: 0},
		"bases":     {word: "bases", result: 0},
		"beat":      {word: "beat", result: 0},
		"blew":      {word: "blue", result: 0},
		"bread":     {word: "bred", result: 0},
		"buy":       {word: "by", result: 0},
		"capital":   {word: "capital", result: 0},
		"ceiling":   {word: "sealing", result: 0},
		"cell":      {word: "sell", result: 0},
		"cent":      {word: "scent", result: 0},
		"cereal":    {word: "serial", result: 0},
		"chews":     {word: "choose", result: 0},
		"Chile":     {word: "chili", result: 0},
		"chord":     {word: "cord", result: 0},
		"cite":      {word: "site", result: 0},
		"close":     {word: "clothes", result: 0},
		"coarse":    {word: "course", result: 0},
		"conduct":   {word: "conduct", result: 0},
		"council":   {word: "counsel", result: 0},
		"creak":     {word: "creek", result: 0},
		"crews":     {word: "cruise", result: 0},
		"days":      {word: "daze", result: 0},
		"dear":      {word: "dee", result: 0},
		"desert":    {word: "desert", result: 0},
		"dew":       {word: "do", result: 0},
		"die":       {word: "dye", result: 0},
		"discreet":  {word: "discrete", result: 0},
		"doe":       {word: "dough", result: 0},
		"dual":      {word: "duel", result: 0},
		"elicit":    {word: "illicit", result: 0},
		"eminent":   {word: "imminent", result: 0},
		"ewe":       {word: "you", result: 0},
		"eye":       {word: "I", result: 0},
		"facts":     {word: "fax", result: 0},
		"fair":      {word: "fare", result: 0},
		"fairy":     {word: "ferry", result: 0},
		"faze":      {word: "phase", result: 0},
		"feat":      {word: "feet", result: 0},
		"find":      {word: "fined", result: 0},
		"fir":       {word: "fur", result: 0},
		"flea":      {word: "flee", result: 0},
		"flew":      {word: "flu", result: 0},
		"flour":     {word: "flower", result: 0},
		"for":       {word: "fore", result: 0},
		"forth":     {word: "fourth", result: 0},
		"foreword":  {word: "forward", result: 0},
		"gene":      {word: "jean", result: 0},
		"gorilla":   {word: "guerrilla", result: 0},
		"grease":    {word: "Greece", result: 0},
		"groan":     {word: "grown", result: 0},
		"hair":      {word: "hare", result: 0},
		"hall":      {word: "haul", result: 0},
		"halve":     {word: "have", result: 0},
		"hay":       {word: "hey", result: 0},
		"heal":      {word: "heel", result: 0},
		"hear":      {word: "here", result: 0},
		"hi":        {word: "high", result: 0},
		"hoarse":    {word: "horse", result: 0},
		"hole":      {word: "whole", result: 0},
		"holey":     {word: "holy", result: 0},
		"hour":      {word: "our", result: 0},
		"knead":     {word: "need", result: 0},
		"knew":      {word: "new", result: 0},
		"knight":    {word: "night", result: 0},
		"knot":      {word: "not", result: 0},
		"know":      {word: "no", result: 0},
		"lead":      {word: "led", result: 0},
		"leased":    {word: "least", result: 0},
		"lessen":    {word: "lesson", result: 0},
		"loan":      {word: "lone", result: 0},
		"made":      {word: "maid", result: 0},
		"mail":      {word: "male", result: 0},
		"material":  {word: "materiel", result: 0},
		"marry":     {word: "merry", result: 0},
		"meat":      {word: "meet", result: 0},
		"mince":     {word: "mints", result: 0},
		"morning":   {word: "mourning", result: 0},
		"none":      {word: "nun", result: 0},
		"oar":       {word: "or", result: 0},
		"oh":        {word: "owe", result: 0},
		"one":       {word: "won", result: 0},
		"overdo":    {word: "overdue", result: 0},
		"pail":      {word: "pale", result: 0},
		"pain":      {word: "pane", result: 0},
		"peace":     {word: "piece", result: 0},
		"patience":  {word: "patients", result: 0},
		"pear":      {word: "pair", result: 0},
		"plain":     {word: "plane", result: 0},
		"pole":      {word: "poll", result: 0},
		"poor":      {word: "pour", result: 0},
		"pray":      {word: "prey", result: 0},
		"principal": {word: "principle", result: 0},
		"rap":       {word: "wrap", result: 0},
		"read":      {word: "red", result: 0},
		"real":      {word: "reel", result: 0},
		"right":     {word: "write", result: 0},
		"ring":      {word: "wring", result: 0},
		"road":      {word: "rode", result: 0},
		"role":      {word: "roll", result: 0},
		"rose":      {word: "rows", result: 0},
		"sail":      {word: "sale", result: 0},
		"scene":     {word: "seen", result: 0},
		"sea":       {word: "see", result: 0},
		"seam":      {word: "seem", result: 0},
		"sew":       {word: "so", result: 0},
		"soar":      {word: "sore", result: 0},
		"sole":      {word: "soul", result: 0},
		"son":       {word: "sun", result: 0},
		"some":      {word: "sum", result: 0},
		"stair":     {word: "stare", result: 0},
		"steal":     {word: "steel", result: 0},
		"suite":     {word: "sweet", result: 0},
		"tail":      {word: "tale", result: 0},
		"their":     {word: "there", result: 0},
		"threw":     {word: "through", result: 0},
		"to":        {word: "too", result: 0},
		"toe":       {word: "tow", result: 0},
		"vary":      {word: "very", result: 0},
		"wail":      {word: "whale", result: 0},
		"waist":     {word: "waste", result: 0},
		"war":       {word: "wore", result: 0},
		"warn":      {word: "worn", result: 0},
		"way":       {word: "weigh", result: 0},
		"we":        {word: "wee", result: 0},
		"weak":      {word: "week", result: 0},
		"wear":      {word: "where", result: 0},
		"weather":   {word: "whether", result: 0},
		"which":     {word: "witch", result: 0},
		"wood":      {word: "would", result: 0},
		"your":      {word: "re", result: 0},
	}
	for str_a, test := range lev_tests {
		res := lev_distance(str_a, test.word)
		t.Logf("%s ^ %s %d == %d", str_a, test.word, res, test.result)
	}
}
